version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: nginx_test
    ports:
      - "8089:80"
    volumes:
      - ./site:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test-secure.rule=Host(`test.haribon.me`)"
      - "traefik.http.routers.test-secure.entrypoints=websecure"
      - "traefik.http.routers.test-secure.tls=true"
      - "traefik.http.routers.test-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.test-secure.loadbalancer.server.port=80"

networks:
  traefik_network:
    external: true
